### ISSUE TITLE
Panic on order create

### ISSUE THREAD

**Issue by sanbornsen** [razorpay/razorpay-go#14]
This is how my code looks like 

```
data := map[string]interface{}{
	"amount":          amountInCents,
	"currency":        "INR",
	"receipt_id":      receiptID,
	"payment_capture": 1,
}
extra := map[string]string{}
body, err := os.RPClient.Order.Create(data, extra)
if err != nil {
	glog.Error("Failed from RazorPay - ", err)
}
```

I am getting this error 
```
Failed from RazorPay - %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

**Comment by sanbornsen** [comment]
I figured that the order create request is returning 400 in the SDK but the same request on curl is returning 200.
What am I missing?

**Comment by shashankvivek** [comment]
Facing similar issue. It has been 14 days for me and no one from razor pay team has responded.  Not at all a good experience while integrating.

**Comment by shashankvivek** [comment]
The documentation is incorrect, it should be `receipt` and not `receipt_id` in payload

```
data := map[string]interface{}{
	"amount":          amountInCents,
	"currency":        "INR",
	"receipt":      receiptID,
	"payment_capture": 1,
}
````

**Comment by shyamkumargithub** [comment]
`This is how my code look like`
```
data := map[string]interface{}{
	"amount":          1000,
	"currency":        "INR",
	"receipt":      receiptID,
	"payment_capture": 1,
}
extraHeader := map[string]string{
		"API_KEY": "SECRET_KEY",
	}
body, err := client.Order.Create(data, extraHeader)
if err != nil {
		log.Println(err)
}
```
`I am getting this error when i create order with incorrect api key or secret key`
```
%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```
`I want to know which type of error is returning`

``` 
Same request on curl returning 401 response code 
```

**Comment by rebootcode** [comment]
401 response code is the error for UnAuthorized error or Invalid Key & Permission Denied

**Comment by amitmahbubani** [comment]
Few issues with error handling in the library. 
1. Errors are not being hydrated correctly [here](https://github.com/razorpay/razorpay-go/blob/0e6c7c357e18a1e70c15d30c925a0a8d2fcd0196/requests/request.go#L119-L121)
2. The `Err` attribute isn't set [here](https://github.com/razorpay/razorpay-go/blob/0e6c7c357e18a1e70c15d30c925a0a8d2fcd0196/requests/request.go#L123-L130), and is read later causing nil pointer errors.

Will patch this in an upcoming release.
