### ISSUE TITLE
Support for payment links

### ISSUE THREAD

**Issue by markandpathak** [razorpay/razorpay-go#21]
Does this SDK support creation of payment links? I could not find any documentation regarding the same.

**Comment by ankitdas13** [comment]
@markandpathak We apologise for the long delay. it has been added in recent release , you can check this [doc](https://github.com/razorpay/razorpay-go/blob/master/documents/paymentLink.md) for your reference .

**Comment by ankitdas13** [comment]
Closing this issue because the feature has already been added in one of the recent release.

Thanks for reporting this issue. If the issue still persists after upgrading, please feel free to re-open it or you can report on the support [portal](https://razorpay.com/support/)
