### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by rajamaniraja** [razorpay/razorpay-go#42]
%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)

**Comment by rajamaniraja** [comment]
PaymentLink Create Method THrows panic .


When i debugged your SDK The error from razorpay is
{"error":{"code":"BAD_REQUEST_ERROR","description":"amount: cannot be blank.","metadata":[],"reason":null,"source":null,"step":null}}

**Comment by ankitdas13** [comment]
@rajamaniraja Sorry for the long delay . Could you please let us know if this issue has been resolved? If not, please let us know we will help you.  also we fixed the exception handling in one of recent release. Please update to the most recent version to resolve this exception handling issue and `amount` is mandatory for creating paymentlink . you can use this [doc](https://github.com/razorpay/razorpay-go/blob/master/documents/paymentLink.md) as a reference

**Comment by ankitdas13** [comment]
Closing this issue because the feature has already been added in one of the recent release. 

Thanks for reporting this issue. If the issue still persists after upgrading, please feel free to re-open it or you can report on the support [portal](https://razorpay.com/support/)
