### ISSUE TITLE
Change amount from int to float in payments request

### ISSUE THREAD

**Issue by medcampus** [razorpay/razorpay-go#5]
func (p *Payment) Capture(id string, amount int, data map[string]interface{}, options map[string]string) (map[string]interface{}, error) {
...
}

update the amount from int to float64

**Comment by medcampus** [comment]
any update on this

**Comment by uday5162** [comment]
any update on this?

**Comment by jitendra-1217** [comment]
Amount values are integers throughout and is in lowest denominations.
For example, for an actual amount of ₹299.35, the value of this field should be 29935.

Closing this but please comment if more questions.
