### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by rajveermalviya** [razorpay/razorpay-go#6]
The last commit was 2 years ago, is this module still use-able for production use?
 
To keep module update to date multiple things are required:

- Go module support [blog.golang.org/using-go-modules](https://blog.golang.org/using-go-modules)
- OSS license for repo, to be able to used by us without any licensing problems. And more importantly for [pkg.go.dev](https://pkg.go.dev/github.com/razorpay/razorpay-go?tab=doc) to generate documentation. For more info check [pkg.go.dev/license-policy](https://pkg.go.dev/license-policy)
- Does API still comply?

**Comment by rebootcode** [comment]
Anyone from team: 
@captn3m0 
@ccrims0n 
@chettyarun 
@ChintanAcharya 
@harshilmathur 
@shashankkumar 
@shashankmehta 
@umanghome 
@utk-spartan 

Any response?

**Comment by amitmahbubani** [comment]
Hi @rajveermalviya: Yes, the SDK remains compatible with our production APIs, but definitely needs an update with respect to the points you brought up and more -- we're on it. Thanks for pointing this out.
